import type { InputCase, ScenarioDef, TopicId } from './typed';

// ── ENTER: the signal field around the central question ─────────────────
// Four vocabularies of automation work. Five of these are selectable topics
// (`topic`) — everything else is an ambient signal: it fills the field, it is
// never interactive, and it is never announced to assistive technology.
// A viewport-dependent balanced subset is chosen in `lib/field.ts`.
export type FieldGroup = 'action' | 'business' | 'ai' | 'creative';

export const FIELD_SIGNALS: { t: string; group: FieldGroup; topic?: TopicId }[] = [
  // what the system does
  { t: 'CAPTURE', group: 'action' },
  { t: 'TRIGGER', group: 'action' },
  { t: 'ROUTE', group: 'action' },
  { t: 'EXECUTE', group: 'action' },
  { t: 'SYNC', group: 'action' },
  { t: 'RESPOND', group: 'action' },
  { t: 'CLASSIFY', group: 'action' },
  { t: 'DECIDE', group: 'action' },
  { t: 'OPTIMIZE', group: 'action' },
  { t: 'MONITOR', group: 'action' },

  // the work that arrives
  { t: 'LEADS', group: 'business', topic: 'leads' },
  { t: 'FOLLOW-UPS', group: 'business' },
  { t: 'SUPPORT', group: 'business', topic: 'support' },
  { t: 'BOOKINGS', group: 'business' },
  { t: 'APPROVALS', group: 'business' },
  { t: 'INVOICES', group: 'business' },
  { t: 'ONBOARDING', group: 'business' },
  { t: 'REPORTS', group: 'business' },
  { t: 'REPORTING', group: 'business', topic: 'reporting' },
  { t: 'SCHEDULING', group: 'business', topic: 'scheduling' },
  { t: 'SOMETHING ELSE', group: 'business', topic: 'other' },

  // what the system understands
  { t: 'READ', group: 'ai' },
  { t: 'UNDERSTAND', group: 'ai' },
  { t: 'ANALYZE', group: 'ai' },
  { t: 'REASON', group: 'ai' },
  { t: 'GENERATE', group: 'ai' },
  { t: 'EXTRACT', group: 'ai' },
  { t: 'SUMMARIZE', group: 'ai' },
  { t: 'PREDICT', group: 'ai' },

  // the work that gets made
  { t: 'DESIGN', group: 'creative' },
  { t: 'BRIEF', group: 'creative' },
  { t: 'COPY', group: 'creative' },
  { t: 'VARIANTS', group: 'creative' },
  { t: 'BRAND', group: 'creative' },
  { t: 'CONTENT', group: 'creative' },
  { t: 'REVIEW', group: 'creative' },
  { t: 'PUBLISH', group: 'creative' },
];

// signal texture: characters and short technical fragments that give the field
// areas of density without competing with the words themselves
const FIELD_GLYPHS = ['·', '·', '·', '.', '.', ':', ':', '+', '=', '/', '×', '#'];

const FIELD_FRAGMENTS = [
  'SPREADSHEET',
  'COPY-PASTE',
  'INBOX',
  'TICKET',
  'STATUS?',
  'MEETING',
  'PHONE',
  'MANUAL',
  'AGAIN',
  'CRM',
];

export { FIELD_GLYPHS, FIELD_FRAGMENTS };

// ── FLOW: executable workflows per input case ───────────────────────────
export const INPUT_CASES: InputCase[] = [
  {
    id: 'lead',
    label: 'NEW LEAD',
    meta: 'WEB FORM // 2:14 PM',
    nodes: [
      { id: 'n0', kind: 'input', label: 'NEW LEAD', sub: 'form submission' },
      { id: 'n1', kind: 'ai', label: 'AI ENRICH', sub: 'company + intent' },
      { id: 'n2', kind: 'decision', label: 'SCORE', sub: 'a ≥ 70?' },
      { id: 'n3a', kind: 'action', label: 'CRM + CALENDAR', sub: 'create + invite' },
      { id: 'n3b', kind: 'action', label: 'NURTURE', sub: 'enqueue sequence' },
      { id: 'n4', kind: 'output', label: 'NOTIFY OWNER', sub: 'slack / email' },
      { id: 'n5', kind: 'output', label: 'LOGGED', sub: 'every step' },
    ],
    edges: [
      { id: 'e0', from: 'n0', to: 'n1' },
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3a', label: 'YES' },
      { id: 'e3', from: 'n2', to: 'n3b', label: 'NO' },
      { id: 'e4', from: 'n3a', to: 'n4' },
      { id: 'e5', from: 'n4', to: 'n5' },
    ],
    branchOn: 'n2',
    branchOk: 'n3a',
    branchNo: 'n3b',
    terminal: 'OWNER NOTIFIED — MEETING PROPOSED',
    logs: [
      'company identified — logistics, ~40 staff',
      'intent: fleet software — relevance 0.9',
      'score 87 → hot path',
      'calendar checked — thu 10:00 free',
      'invite sent, owner notified',
    ],
  },
  {
    id: 'question',
    label: 'CUSTOMER QUESTION',
    meta: 'SUPPORT INBOX // 9:41 AM',
    nodes: [
      { id: 'n0', kind: 'input', label: 'QUESTION', sub: 'email received' },
      { id: 'n1', kind: 'ai', label: 'AI READS', sub: 'classify intent' },
      { id: 'n2', kind: 'data', label: 'KNOWLEDGE BASE', sub: 'semantic search' },
      { id: 'n3', kind: 'decision', label: 'CONFIDENT?', sub: 'p ≥ 0.9' },
      { id: 'n4a', kind: 'action', label: 'DRAFT REPLY', sub: 'human approval' },
      { id: 'n4b', kind: 'action', label: 'ROUTE HUMAN', sub: 'with context' },
      { id: 'n5', kind: 'output', label: 'RESPOND', sub: '4-min median' },
    ],
    edges: [
      { id: 'e0', from: 'n0', to: 'n1' },
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3' },
      { id: 'e3', from: 'n3', to: 'n4a', label: 'YES' },
      { id: 'e4', from: 'n3', to: 'n4b', label: 'NO' },
      { id: 'e5', from: 'n4a', to: 'n5' },
    ],
    branchOn: 'n3',
    branchOk: 'n4a',
    branchNo: 'n4b',
    terminal: 'REPLY DRAFTED — WAITING ON ONE HUMAN YES',
    logs: [
      'intent classified: billing question',
      '3 knowledge articles matched',
      'confidence 0.94 → draft path',
      'tone check passed',
      'draft queued for approval',
    ],
  },
  {
    id: 'invoice',
    label: 'INVOICE',
    meta: 'ACCOUNTS PAYABLE // MONDAY',
    nodes: [
      { id: 'n0', kind: 'input', label: 'INVOICE', sub: 'pdf attachment' },
      { id: 'n1', kind: 'ai', label: 'AI EXTRACTS', sub: 'vendor / amount' },
      { id: 'n2', kind: 'data', label: 'MATCH LEDGER', sub: 'purchase order' },
      { id: 'n3', kind: 'decision', label: '3-WAY MATCH', sub: 'exact?' },
      { id: 'n4a', kind: 'action', label: 'SCHEDULE PAY', sub: 'net-30' },
      { id: 'n4b', kind: 'action', label: 'FLAG DIFF', sub: 'to finance' },
      { id: 'n5', kind: 'output', label: 'ARCHIVE', sub: 'audit trail' },
    ],
    edges: [
      { id: 'e0', from: 'n0', to: 'n1' },
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3' },
      { id: 'e3', from: 'n3', to: 'n4a', label: 'YES' },
      { id: 'e4', from: 'n3', to: 'n4b', label: 'NO' },
      { id: 'e5', from: 'n4a', to: 'n5' },
      { id: 'e6', from: 'n4b', to: 'n5' },
    ],
    branchOn: 'n3',
    branchOk: 'n4a',
    branchNo: 'n4b',
    terminal: 'PAYMENT SCHEDULED — PAPERWORK GONE',
    logs: [
      'fields extracted: vendor, amount, due date',
      'purchase order #2231 found',
      'amounts match — variance 0.00',
      'scheduled: next net-30 cycle',
      'archived with audit trail',
    ],
  },
  {
    id: 'meeting',
    label: 'MEETING REQUEST',
    meta: 'CALENDAR // ANY TIME',
    nodes: [
      { id: 'n0', kind: 'input', label: 'REQUEST', sub: '“find us 30 min”' },
      { id: 'n1', kind: 'ai', label: 'AI PARSES', sub: 'attendees + duration' },
      { id: 'n2', kind: 'data', label: 'CALENDARS', sub: '5 people' },
      { id: 'n3', kind: 'decision', label: 'OVERLAP?', sub: 'this week' },
      { id: 'n4a', kind: 'action', label: 'BOOK', sub: 'send invites' },
      { id: 'n4b', kind: 'action', label: 'PROPOSE', sub: '2 alternatives' },
      { id: 'n5', kind: 'output', label: 'CONFIRMED', sub: 'zero chains' },
    ],
    edges: [
      { id: 'e0', from: 'n0', to: 'n1' },
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3' },
      { id: 'e3', from: 'n3', to: 'n4a', label: 'YES' },
      { id: 'e4', from: 'n3', to: 'n4b', label: 'NO' },
      { id: 'e5', from: 'n4a', to: 'n5' },
      { id: 'e6', from: 'n4b', to: 'n5' },
    ],
    branchOn: 'n3',
    branchOk: 'n4a',
    branchNo: 'n4b',
    terminal: 'BOOKED — 9 EMAILS THAT NEVER HAPPENED',
    logs: [
      '5 calendars read in parallel',
      'overlap found: thu 15:00–15:30',
      'room holds 8 — fine',
      'invites sent automatically',
      'zero back-and-forth required',
    ],
  },
  {
    id: 'report',
    label: 'REPORT REQUEST',
    meta: 'OPS // FRIDAY 4 PM',
    nodes: [
      { id: 'n0', kind: 'input', label: '“SEND WEEKLY”', sub: 'standing request' },
      { id: 'n1', kind: 'ai', label: 'AI QUERIES', sub: 'the right sources' },
      { id: 'n2', kind: 'data', label: '3 DATA SOURCES', sub: 'crm / billing / ops' },
      { id: 'n3', kind: 'decision', label: 'ANOMALY?', sub: 'vs trailing 4wk' },
      { id: 'n4a', kind: 'action', label: 'COMPOSE REPORT', sub: 'with commentary' },
      { id: 'n4b', kind: 'action', label: 'ADD ALERT', sub: 'flag the anomaly' },
      { id: 'n5', kind: 'output', label: 'DISTRIBUTE', sub: 'to the team' },
    ],
    edges: [
      { id: 'e0', from: 'n0', to: 'n1' },
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3' },
      { id: 'e3', from: 'n3', to: 'n4b', label: 'YES' },
      { id: 'e4', from: 'n3', to: 'n4a', label: 'NO' },
      { id: 'e5', from: 'n4a', to: 'n5' },
      { id: 'e6', from: 'n4b', to: 'n5' },
    ],
    branchOn: 'n3',
    branchOk: 'n4b',
    branchNo: 'n4a',
    terminal: 'SENT — 40 MINUTES NOBODY SPENT',
    logs: [
      'sources synced: crm, billing, ops',
      'week-over-week computed',
      'anomaly: refund spike tue (+18%)',
      'commentary drafted around anomaly',
      'delivered to team channel',
    ],
  },
];

// ── SCENARIOS: industries ───────────────────────────────────────────────
export const SCENARIOS: ScenarioDef[] = [
  {
    id: 'realestate',
    code: 'SCN-01',
    name: 'REAL ESTATE',
    problem: 'Leads go cold while agents chase paperwork.',
    needs: 'LEAD CAPTURE',
    handles: 'AI QUALIFICATION',
    returns: 'AGENT READY TO SHOW',
    nodes: [
      { id: 's0', label: 'LEAD', kind: 'input' },
      { id: 's1', label: 'AI QUALIFY', kind: 'ai' },
      { id: 's2', label: 'PROPERTY DATA', kind: 'data' },
      { id: 's3', label: 'MATCH', kind: 'decision' },
      { id: 's4', label: 'CRM', kind: 'action' },
      { id: 's5', label: 'FOLLOW-UP', kind: 'output' },
    ],
    links: [
      ['s0', 's1'],
      ['s1', 's2'],
      ['s1', 's3'],
      ['s3', 's4'],
      ['s4', 's5'],
      ['s2', 's3'],
    ],
    sequence: ['s0', 's1', 's2', 's3', 's4', 's5'],
    terminal: 'VIEWING BOOKED BEFORE THE LEAD WENT LUKEWARM',
  },
  {
    id: 'ecommerce',
    code: 'SCN-02',
    name: 'E-COMMERCE',
    problem: 'Orders, stock and support live in three different worlds.',
    needs: 'ORDER EVENT',
    handles: 'AI ANALYSIS',
    returns: 'CUSTOMER INFORMED',
    nodes: [
      { id: 's0', label: 'ORDER', kind: 'input' },
      { id: 's1', label: 'CUSTOMER DATA', kind: 'data' },
      { id: 's2', label: 'AI ANALYSIS', kind: 'ai' },
      { id: 's3', label: 'INVENTORY', kind: 'decision' },
      { id: 's4', label: 'FULFILLMENT', kind: 'action' },
      { id: 's5', label: 'NOTIFICATION', kind: 'output' },
    ],
    links: [
      ['s0', 's2'],
      ['s1', 's2'],
      ['s2', 's3'],
      ['s3', 's4'],
      ['s4', 's5'],
    ],
    sequence: ['s0', 's1', 's2', 's3', 's4', 's5'],
    terminal: 'ORDER OUT THE DOOR, CUSTOMER ALREADY TOLD',
  },
  {
    id: 'healthcare',
    code: 'SCN-03',
    name: 'HEALTHCARE',
    problem: 'Front desks drown in appointment admin.',
    needs: 'PATIENT REQUEST',
    handles: 'AI TRIAGE',
    returns: 'APPOINTMENT CONFIRMED',
    nodes: [
      { id: 's0', label: 'PATIENT REQ', kind: 'input' },
      { id: 's1', label: 'AI TRIAGE', kind: 'ai' },
      { id: 's2', label: 'RECORDS', kind: 'data' },
      { id: 's3', label: 'URGENCY', kind: 'decision' },
      { id: 's4', label: 'SCHEDULING', kind: 'action' },
      { id: 's5', label: 'REMINDER', kind: 'output' },
    ],
    links: [
      ['s0', 's1'],
      ['s1', 's2'],
      ['s1', 's3'],
      ['s3', 's4'],
      ['s4', 's5'],
      ['s2', 's3'],
    ],
    sequence: ['s0', 's1', 's2', 's3', 's4', 's5'],
    terminal: 'RIGHT CLINICIAN, RIGHT SLOT, NO PHONE QUEUE',
  },
  {
    id: 'education',
    code: 'SCN-04',
    name: 'EDUCATION',
    problem: 'Enquiries arrive at 2 AM. Staff reply at 11.',
    needs: 'STUDENT ENQUIRY',
    handles: 'AI ADVISING',
    returns: 'ENROLMENT MOVING',
    nodes: [
      { id: 's0', label: 'ENQUIRY', kind: 'input' },
      { id: 's1', label: 'AI ADVISE', kind: 'ai' },
      { id: 's2', label: 'COURSE DATA', kind: 'data' },
      { id: 's3', label: 'ELIGIBILITY', kind: 'decision' },
      { id: 's4', label: 'ENROLMENT', kind: 'action' },
      { id: 's5', label: 'NURTURE', kind: 'output' },
    ],
    links: [
      ['s0', 's1'],
      ['s1', 's2'],
      ['s1', 's3'],
      ['s3', 's4'],
      ['s4', 's5'],
      ['s2', 's3'],
    ],
    sequence: ['s0', 's1', 's2', 's3', 's4', 's5'],
    terminal: 'ANSWERED AT 2:01 AM. ENROLLED BY BREAKFAST.',
  },
  {
    id: 'services',
    code: 'SCN-05',
    name: 'PROFESSIONAL SERVICES',
    problem: 'Billable hours die in admin and intake.',
    needs: 'NEW CLIENT INTAKE',
    handles: 'AI INTAKE',
    returns: 'ENGAGEMENT OPENED',
    nodes: [
      { id: 's0', label: 'INTAKE', kind: 'input' },
      { id: 's1', label: 'AI INTAKE', kind: 'ai' },
      { id: 's2', label: 'CONFLICT CHECK', kind: 'decision' },
      { id: 's3', label: 'DOCUMENTS', kind: 'data' },
      { id: 's4', label: 'ENGAGEMENT', kind: 'action' },
      { id: 's5', label: 'KICKOFF', kind: 'output' },
    ],
    links: [
      ['s0', 's1'],
      ['s1', 's2'],
      ['s1', 's3'],
      ['s2', 's4'],
      ['s3', 's4'],
      ['s4', 's5'],
    ],
    sequence: ['s0', 's1', 's3', 's2', 's4', 's5'],
    terminal: 'CONFLICTS CLEARED, KICKOFF BOOKED SAME DAY',
  },
  {
    id: 'local',
    code: 'SCN-06',
    name: 'LOCAL BUSINESS',
    problem: 'One person answers every call while doing the work.',
    needs: 'INBOUND CALL',
    handles: 'AI RECEPTION',
    returns: 'JOB ON THE CALENDAR',
    nodes: [
      { id: 's0', label: 'CALL/MSG', kind: 'input' },
      { id: 's1', label: 'AI RECEPTION', kind: 'ai' },
      { id: 's2', label: 'SERVICE AREA', kind: 'data' },
      { id: 's3', label: 'JOB TYPE', kind: 'decision' },
      { id: 's4', label: 'BOOK JOB', kind: 'action' },
      { id: 's5', label: 'CONFIRM SMS', kind: 'output' },
    ],
    links: [
      ['s0', 's1'],
      ['s1', 's2'],
      ['s1', 's3'],
      ['s3', 's4'],
      ['s4', 's5'],
      ['s2', 's3'],
    ],
    sequence: ['s0', 's1', 's2', 's3', 's4', 's5'],
    terminal: 'JOB BOOKED WHILE THE VAN WAS STILL MOVING',
  },
  {
    id: 'design',
    code: 'SCN-07',
    name: 'DESIGN STUDIO',
    problem: 'Every brief waits for a designer to start from a blank canvas.',
    needs: 'DESIGN BRIEF',
    handles: 'AI DESIGN PASS',
    returns: 'CONCEPTS IN REVIEW',
    nodes: [
      { id: 's0', label: 'BRIEF', kind: 'input' },
      { id: 's1', label: 'AI DESIGN', kind: 'ai' },
      { id: 's2', label: 'BRAND LIBRARY', kind: 'data' },
      { id: 's3', label: 'VARIANTS', kind: 'decision' },
      { id: 's4', label: 'DESIGN TOOL', kind: 'action' },
      { id: 's5', label: 'HANDOFF', kind: 'output' },
    ],
    links: [
      ['s0', 's1'],
      ['s1', 's2'],
      ['s1', 's3'],
      ['s3', 's4'],
      ['s4', 's5'],
      ['s2', 's3'],
    ],
    sequence: ['s0', 's1', 's2', 's3', 's4', 's5'],
    terminal: 'SIX DIRECTIONS WAITING BEFORE THE KICKOFF ENDED',
  },
];

// ── WHAT IF: the big convergence ────────────────────────────────────────
export const CONVERGE_SOURCES = [
  'EMAIL',
  'CRM',
  'CALENDAR',
  'DATABASE',
  'PAYMENTS',
  'MESSAGING',
  'SPREADSHEETS',
];

export const INTEGRATION_TOOLS = [
  { id: 'crm', label: 'CRM', desc: 'customer records' },
  { id: 'email', label: 'EMAIL', desc: 'inbox + outreach' },
  { id: 'sheets', label: 'SPREADSHEETS', desc: 'the world’s database' },
  { id: 'calendar', label: 'CALENDAR', desc: 'time itself' },
  { id: 'billing', label: 'BILLING', desc: 'invoices + payments' },
  { id: 'chat', label: 'MESSAGING', desc: 'slack, whatsapp, sms' },
  { id: 'db', label: 'DATABASE', desc: 'your systems of record' },
  { id: 'api', label: 'ANY API', desc: 'everything else' },
];
